name: Deploy Project
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'apply or destroy'
        required: true

      ami_id:
        description: 'AMI ID'
        required: true

      instance_type:
        description: 'Instance Type'
        required: true

      key_name:
        description: 'Key Pair Name'
        required: true

      aws_region:
        description: 'AWS Region'
        required: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::060795920646:role/github-actions-role
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Run a deployment placeholder
        run: echo "Deployment workflow triggered"
      - name: Show Input Values
        run: |
          echo "AMI ID: ${{ github.event.inputs.ami_id }}"
          echo "Instance Type: ${{ github.event.inputs.instance_type }}"
          echo "Key Name: ${{ github.event.inputs.key_name }}"
          echo "AWS Region: ${{ github.event.inputs.aws_region }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform --version


      - name: Terraform Init
        working-directory: terraform
        run: terraform init